version: '3.1'

services:

  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    ports:
      - 1234:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
